const otherPets = [
  {
    id: 1,
    image:
      "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQgByBT5IiAT_a2x9pUVb4VMoOrlzHH7Jrzj-HB5jzHlR4lNLMS",
    nameImage: "dog8.jpg",
    name: "Shadow",
    age: "5 anni",
    city: "Torino",
    description: "Un cane leale e protettivo.",
    razza: "Pastore Tedesco",
    type: "Cane",
    size: "Taglia grande",
    owner: {
      name: "Francesco Grigio",
      phone: "320-876-5432",
      email: "francesco.grigio@example.com",
    },
  },
  {
    id: 2,
    image: "https://www.petportal.it/wp-content/uploads/2023/06/cat7.jpg",
    nameImage: "cat7.jpg",
    name: "Simba",
    age: "8 anni",
    city: "Bari",
    description: "Un gatto tranquillo e affettuoso.",
    razza: "Persiano",
    type: "Gatto",
    owner: {
      name: "Giovanna Viola",
      phone: "327-654-3211",
      email: "giovanna.viola@example.com",
    },
  },
  {
    id: 3,
    image: "https://www.fidopets.it/wp-content/uploads/2023/07/dog9.jpg",
    nameImage: "dog9.jpg",
    name: "Duke",
    age: "1 anno",
    city: "Torino",
    description: "Un cucciolo energico e giocoso.",
    razza: "Bulldog Francese",
    type: "Cane",
    size: "Taglia piccola",
    owner: {
      name: "Alessandro Nero",
      phone: "322-543-7890",
      email: "alessandro.nero@example.com",
    },
  },
  {
    id: 4,
    image: "https://www.gattolandia.it/wp-content/uploads/2023/08/cat8.jpg",
    nameImage: "cat8.jpg",
    name: "Tigro",
    age: "6 mesi",
    city: "Firenze",
    description: "Un gattino curioso e avventuroso.",
    razza: "Bengala",
    type: "Gatto",
    owner: {
      name: "Lorenzo Blu",
      phone: "321-987-6544",
      email: "lorenzo.blu@example.com",
    },
  },
  {
    id: 5,
    image: "https://www.animalhouse.it/wp-content/uploads/2023/09/dog10.jpg",
    nameImage: "dog10.jpg",
    name: "Bruno",
    age: "4 anni",
    city: "Roma",
    description: "Un cane affettuoso e obbediente.",
    razza: "Rottweiler",
    type: "Cane",
    size: "Taglia grande",
    owner: {
      name: "Marta Rossi",
      phone: "324-567-8902",
      email: "marta.rossi@example.com",
    },
  },
  {
    id: 6,
    image: "https://www.gattitaliani.it/wp-content/uploads/2023/10/cat9.jpg",
    nameImage: "cat9.jpg",
    name: "Oreo",
    age: "3 anni",
    city: "Napoli",
    description: "Un gatto socievole e affettuoso.",
    razza: "Siberiano",
    type: "Gatto",
    owner: {
      name: "Carla Verde",
      phone: "315-789-6544",
      email: "carla.verde@example.com",
    },
  },
  {
    id: 7,
    image: "https://www.adorabileamico.it/wp-content/uploads/2023/11/dog11.jpg",
    nameImage: "dog11.jpg",
    name: "Rex",
    age: "6 anni",
    city: "Milano",
    description: "Un cane fedele e coraggioso.",
    razza: "Dobermann",
    type: "Cane",
    size: "Taglia grande",
    owner: {
      name: "Marco Bianchi",
      phone: "316-547-8391",
      email: "marco.bianchi@example.com",
    },
  },
  {
    id: 8,
    image: "https://www.petslover.it/wp-content/uploads/2023/12/cat10.jpg",
    nameImage: "cat10.jpg",
    name: "Lily",
    age: "5 anni",
    city: "Verona",
    description: "Una gatta dolce e coccolona.",
    razza: "Ragdoll",
    type: "Gatto",
    owner: {
      name: "Simona Gialli",
      phone: "318-765-4322",
      email: "simona.gialli@example.com",
    },
  },
  {
    id: 9,
    image: "https://www.amicianimali.it/wp-content/uploads/2023/06/dog12.jpg",
    nameImage: "dog12.jpg",
    name: "Buddy",
    age: "3 anni",
    city: "Cagliari",
    description: "Un cane affettuoso e vivace.",
    razza: "Border Collie",
    type: "Cane",
    size: "Taglia media",
    owner: {
      name: "Paolo Rossi",
      phone: "327-654-3212",
      email: "paolo.rossi@example.com",
    },
  },
  {
    id: 10,
    image: "https://www.gattomiao.it/wp-content/uploads/2023/07/cat11.jpg",
    nameImage: "cat11.jpg",
    name: "Milo",
    age: "2 anni",
    city: "Trieste",
    description: "Un gatto dolce e giocoso.",
    razza: "British Shorthair",
    type: "Gatto",
    owner: {
      name: "Elena Bianchi",
      phone: "329-678-1235",
      email: "elena.bianchi@example.com",
    },
  },
  {
    id: 11,
    image: "https://www.caneamico.it/wp-content/uploads/2023/08/dog13.jpg",
    nameImage: "dog13.jpg",
    name: "Charlie",
    age: "1 anno",
    city: "Perugia",
    description: "Un cucciolo energico e affettuoso.",
    razza: "Cocker Spaniel",
    type: "Cane",
    size: "Taglia piccola",
    owner: {
      name: "Giovanni Verde",
      phone: "312-456-7891",
      email: "giovanni.verde@example.com",
    },
  },
];
export default otherPets;
